# ===============================
# Application
# ===============================
spring.application.name=auth-service

# ===============================
# Server
# ===============================
server.port=8081

# ===============================
# Datasource PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5434/auth_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Redis
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ===============================
# Security - OAuth2 Resource Server (Keycloak)
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/visioconference
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/visioconference/protocol/openid-connect/certs

# ===============================
# Keycloak (Admin / Client Config)
# ===============================
keycloak.realm=visioconference
keycloak.auth-server-url=http://localhost:8180
keycloak.resource=visioconference-backend
keycloak.credentials.secret=xHFgVby8cTcu7L0H23DtFhLhfuDcbiem

# ===============================
# Logging
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.keycloak=INFO
logging.level.com.example.auth_service=DEBUG